### ISSUE TITLE
[Suggestion] Make it compatible with qb-management

### ISSUE THREAD

**Issue by Krizmatic** [Kmack710/710-jobCreator#1]
Make it work with the new qb-management script [https://github.com/qbcore-framework/qb-management](url)

**Comment by Kmack710** [comment]
> Make it work with the new qb-management script [https://github.com/qbcore-framework/qb-management](url)

qb-management is basically the same as qb-bossmenu and qb-gangs so its still compatible. And works the same as it did before qb-management. 

They still load bossmenu locations the exact same way so its not possible to refresh it like QBCore can be. :(
